# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "zenguard"
client_id = "5ff86e357df7fd8d1965d76a97182bad"
application_url = "https://localhost"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_customers,write_customers,read_content,write_content,read_shipping,write_shipping"

[auth]
redirect_urls = [
  "https://localhost/auth/callback"
]

[webhooks]
api_version = "2026-01"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
